version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 600
      runas: ec2-user
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 600
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 600
      runas: ec2-user
